### ISSUE TITLE
AttributeError: module 'PyWSD.wsd_common' has no attribute 'init'

### ISSUE THREAD

**Issue by yacosta738** [roncapat/WSD-python#8]
I tried to run the demo code in wsd_scan_operations but init function is not found in wsd_common

```
Traceback (most recent call last):
  File "/home/acosta/Projects/scanner/WSD-python/src/PyWSD/wsd_scan__operations.py", line 329, in <module>
    __demo()
  File "/home/acosta/Projects/scanner/WSD-python/src/PyWSD/wsd_scan__operations.py", line 288, in __demo
    wsd_common.init()
AttributeError: module 'PyWSD.wsd_common' has no attribute 'init'
```

**Comment by mwllgr** [comment]
May I ask, do you remember how you solved this?
